Frameworks_ThatSneakerShop/Models/Shoe.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;

namespace Frameworks_ThatSneakerShop.Models {
    public class Shoe {
        [Key]
        public int ShoeId { get; set; }

        [Required]
        [Display(Name = "Name")]
        public string ShoeName { get; set; }

        [Required]
        [Display(Name = "Description")]
        public string ShoeDescription { get; set; }

        [Required]
        [DataType(DataType.Currency)]
        [Display(Name = "Price")]
        public float ShoePrice { get; set; }

        [Required]
        public int Stock { get; set; }

        [ForeignKey("CategoryId")]
        public Category Category { get; set; }
        public int CategoryId { get; set; }

        [DefaultValue(false)]
        [Display(Name = "Available")]
        public bool Hidden { get; set; }
    }
}

Frameworks_ThatSneakerShop/Controllers/ShoesController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Frameworks_ThatSneakerShop.Data;
using Frameworks_ThatSneakerShop.Models;
using System.Linq;
using System.Text.RegularExpressions;

namespace Frameworks_ThatSneakerShop.Controllers
{
    public class ShoesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ShoesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Shoes
        public async Task<IActionResult> Index(string searchField = "") {


            List<Shoe> shoes = await _context.Shoe.
                                    Where(g => g.Category.CategoryName.Contains(searchField) || searchField != " ")
                                    .Include(g => g.Category).ToListAsync();
            ViewData["searchField"] = searchField;
            return View(shoes);

            //return View(await applicationDbContext.ToListAsync());
        }

        // GET: Shoes/Details/5
        public async Task<IActionResult> Details(int? id) {
            if (id == null || _context.Shoe == null)
            {
                return NotFound();
            }

            var shoe = await _context.Shoe
                .FirstOrDefaultAsync(m => m.ShoeId == id);
            if (shoe == null)
            {
                return NotFound();
            }

            return View(shoe);
        }

        // GET: Shoes/Create
        public IActionResult Create() {
            ViewData["CategoryId"] = new SelectList(_context.Category, "CategoryId", "CategoryName");
            return View();
        }

        // POST: Shoes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ShoeId,CategoryId")] Shoe shoe)
        {
            if (ModelState.IsValid)
            {
                _context.Add(shoe);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_context.Category, "CategoryId", "CategoryName", shoe.CategoryId);
            return View(shoe);
        }

        // GET: Shoes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Whislist == null)
            {
                return NotFound();
            }

            var shoe = await _context.Shoe.FindAsync(id);
            if (shoe == null)
            {
                return NotFound();
            }
            ViewData["CategoryId"] = new SelectList(_context.Category, "CategoryId", "CategoryName", shoe.CategoryId);

            return View(shoe);
        }

        // POST: Shoes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ShoeId, CategoryId")] Shoe shoe)
        {
            if (id != shoe.ShoeId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(shoe);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ShoeExists(shoe.ShoeId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_context.Category, "CategoryId", "CategoryName", shoe.CategoryId);
            return View(shoe);
        }

        // GET: Shoes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            //if (id == null || _context.Shoe == null)
            //{
            //    return NotFound();
            //}

            //var shoe = await _context.Shoe
            //    .Include(w => w.Category)
            //    .FirstOrDefaultAsync(m => m.ShoeId == id);
            //if (shoe == null)
            //{
            //    return NotFound();
            //}

            //return View(shoe);

            var shoe = _context.Shoe.Find(id);
            if (shoe == null)
            {
                // Category not found
                return NotFound();
            }

            // Ik gebruik gewoon mijn property bool Hidden om deze te verstoppen 
            // In de cshtml doe ik een if else structuur om deze te verstoppen of te tonen 
            shoe.Hidden = true;
            _context.SaveChanges();

            // Redirect the user back to the view
            return RedirectToAction(nameof(Index));
        }

        [HttpPost, ActionName("UpdateData")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateData(bool hidden)
        {
            var shoes = _context.Shoe.Where(p => p.Hidden == true);

            foreach (var shoe in shoes)
            {
                shoe.Hidden = false;
            }
            _context.SaveChanges();

            // Redirect the user back to the view 
            return RedirectToAction(nameof(Index));
        }


        // POST: Shoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Shoe == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Shoe'  is null.");
            }
            var shoe = await _context.Shoe.FindAsync(id);
            if (shoe != null)
            {
                _context.Shoe.Remove(shoe);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ShoeExists(int id)
        {
          return _context.Shoe.Any(e => e.ShoeId == id);
        }

    }
}

Frameworks_ThatSneakerShop/Views/Shoes/Create.cshtml
@model Frameworks_ThatSneakerShop.Models.Shoe

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Shoe</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ShoeName" class="control-label"></label>
                <input asp-for="ShoeName" class="form-control" />
                <span asp-validation-for="ShoeName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ShoeDescription" class="control-label"></label>
                <input asp-for="ShoeDescription" class="form-control" />
                <span asp-validation-for="ShoeDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ShoePrice" class="control-label"></label>
                <input asp-for="ShoePrice" class="form-control" />
                <span asp-validation-for="ShoePrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Stock" class="control-label"></label>
                <input asp-for="Stock" class="form-control" />
                <span asp-validation-for="Stock" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Frameworks_ThatSneakerShop/Views/Shoes/Delete.cshtml
@model Frameworks_ThatSneakerShop.Models.Shoe

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Shoe</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ShoeName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ShoeName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ShoeDescription)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ShoeDescription)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ShoePrice)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ShoePrice)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Stock)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Stock)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ShoeId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Frameworks_ThatSneakerShop/Views/Shoes/Details.cshtml
@model Frameworks_ThatSneakerShop.Models.Shoe

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Shoe</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ShoeName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ShoeName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ShoeDescription)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ShoeDescription)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ShoePrice)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ShoePrice)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Stock)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Stock)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.ShoeId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Frameworks_ThatSneakerShop/Views/Shoes/Edit.cshtml
@model Frameworks_ThatSneakerShop.Models.Shoe

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Shoe</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ShoeId" />
            <div class="form-group">
                <label asp-for="ShoeName" class="control-label"></label>
                <input asp-for="ShoeName" class="form-control" />
                <span asp-validation-for="ShoeName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ShoeDescription" class="control-label"></label>
                <input asp-for="ShoeDescription" class="form-control" />
                <span asp-validation-for="ShoeDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ShoePrice" class="control-label"></label>
                <input asp-for="ShoePrice" class="form-control" />
                <span asp-validation-for="ShoePrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Stock" class="control-label"></label>
                <input asp-for="Stock" class="form-control" />
                <span asp-validation-for="Stock" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryId" class="control-label"></label>
                <select asp-for="CategoryId" class="form-control" asp-items="ViewBag.CategoryId"></select>
                <span asp-validation-for="CategoryId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Frameworks_ThatSneakerShop/Views/Shoes/Filter.cshtml
@model IEnumerable<Frameworks_ThatSneakerShop.Models.Shoe>

@{
    ViewData["Title"] = "Filter";
}


<h1>Filterd view</h1>

@foreach (var item in Model) {
    <div>@item.ShoeName</div>
    <div>@item.ShoeDescription</div>
    <div>@item.ShoePrice</div>
    <div>@item.Stock</div>
}

Frameworks_ThatSneakerShop/Views/Shoes/Index.cshtml
@model IEnumerable<Frameworks_ThatSneakerShop.Models.Shoe>

@{
    ViewData["Title"] = "Index";
}


<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>

<form method="get" asp-action="Index" asp-controller="Shoe">
    <p>
        <input type="text" name="search" value=@ViewData["searchField"] />
        <input type="submit" value = "Search" />
    </p>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ShoeName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ShoeDescription)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ShoePrice)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Stock)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Category)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
            <tr>
                @if (item.Hidden == false)
                {

                    <td>
                        @Html.DisplayFor(modelItem => item.ShoeName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ShoeDescription)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ShoePrice)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Stock)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Category.CategoryName)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.ShoeId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ShoeId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ShoeId">Delete</a>
            </td>
            }
                    
        </tr>
}


        @using (Html.BeginForm("UpdateData", "Shoes", FormMethod.Post))
        {
            <button type="submit">Show All Data</button>
        }
    </tbody>
</table>