Frameworks_ThatSneakerShop/Models/Whislist.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Frameworks_ThatSneakerShop.Models {
    public class Whislist {
        [Key]
        public int WhislistId { get; set; }

        [ForeignKey ("ShoeId")]
        public Shoe Shoe { get; set; }
        public int ShoeId { get; set; }

        [DefaultValue(false)]
        [Display(Name = "Available")]
        public bool Hidden { get; set; }
    }
}

Frameworks_ThatSneakerShop/Controllers/WhislistsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Frameworks_ThatSneakerShop.Data;
using Frameworks_ThatSneakerShop.Models;

namespace Frameworks_ThatSneakerShop.Controllers
{
    public class WhislistsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public WhislistsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Whislists
        public async Task<IActionResult> Index(string searchField = "") {
            List<Whislist> lists = await _context.Whislist.
                                   Where(g => g.Shoe.ShoeName.Contains(searchField) || searchField != " ")
                                   .Include(g => g.Shoe).ToListAsync();
            ViewData["searchField"] = searchField;
            return View(lists);

            //var applicationDbContext = _context.Whislist.Include(w => w.Shoe);
            //return View(await applicationDbContext.ToListAsync());
        }

        // GET: Whislists/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Whislist == null)
            {
                return NotFound();
            }

            var whislist = await _context.Whislist
                .Include(w => w.Shoe)
                .FirstOrDefaultAsync(m => m.WhislistId == id);
            if (whislist == null)
            {
                return NotFound();
            }

            return View(whislist);
        }

        // GET: Whislists/Create
        public IActionResult Create()
        {
            ViewData["ShoeId"] = new SelectList(_context.Shoe, "ShoeId", "ShoeDescription");
            return View();
        }

        // POST: Whislists/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("WhislistId,ShoeId")] Whislist whislist)
        {
            if (ModelState.IsValid)
            {
                _context.Add(whislist);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ShoeId"] = new SelectList(_context.Shoe, "ShoeId", "ShoeDescription", whislist.ShoeId);
            return View(whislist);
        }

        // GET: Whislists/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Whislist == null)
            {
                return NotFound();
            }

            var whislist = await _context.Whislist.FindAsync(id);
            if (whislist == null)
            {
                return NotFound();
            }
            ViewData["ShoeId"] = new SelectList(_context.Shoe, "ShoeId", "ShoeDescription", whislist.ShoeId);
            return View(whislist);
        }

        // POST: Whislists/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("WhislistId,ShoeId")] Whislist whislist)
        {
            if (id != whislist.WhislistId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(whislist);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!WhislistExists(whislist.WhislistId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ShoeId"] = new SelectList(_context.Shoe, "ShoeId", "ShoeDescription", whislist.ShoeId);
            return View(whislist);
        }

        // GET: Whislists/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            //if (id == null || _context.Whislist == null)
            //{
            //    return NotFound();
            //}

            //var whislist = await _context.Whislist
            //    .Include(w => w.Shoe)
            //    .FirstOrDefaultAsync(m => m.WhislistId == id);
            //if (whislist == null)
            //{
            //    return NotFound();
            //}

            //return View(whislist);

            var whislist = _context.Whislist.Find(id);
            if (whislist == null)
            {
                // Category not found
                return NotFound();
            }

            // Ik gebruik gewoon mijn property bool Hidden om deze te verstoppen 
            // In de cshtml doe ik een if else structuur om deze te verstoppen of te tonen 
            whislist.Hidden = true;
            _context.SaveChanges();

            // Redirect the user back to the view
            return RedirectToAction(nameof(Index));
        }


        [HttpPost, ActionName("UpdateData")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateData(bool hidden)
        {
            var whislists = _context.Whislist.Where(p => p.Hidden == true);

            foreach (var wishlist in whislists)
            {
                wishlist.Hidden = false;
            }
            _context.SaveChanges();

            // Redirect the user back to the view 
            return RedirectToAction(nameof(Index));
        }


        // POST: Whislists/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Whislist == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Whislist'  is null.");
            }
            var whislist = await _context.Whislist.FindAsync(id);
            if (whislist != null)
            {
                _context.Whislist.Remove(whislist);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool WhislistExists(int id)
        {
          return _context.Whislist.Any(e => e.WhislistId == id);
        }
    }
}

Frameworks_ThatSneakerShop/Views/Whislists/Create.cshtml
@model Frameworks_ThatSneakerShop.Models.Whislist

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Whislist</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ShoeId" class="control-label"></label>
                <select asp-for="ShoeId" class ="form-control" asp-items="ViewBag.ShoeId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Frameworks_ThatSneakerShop/Views/Whislists/Delete.cshtml
@model Frameworks_ThatSneakerShop.Models.Whislist

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Whislist</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Shoe)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Shoe.ShoeDescription)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="WhislistId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Frameworks_ThatSneakerShop/Views/Whislists/Details.cshtml
@model Frameworks_ThatSneakerShop.Models.Whislist

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Whislist</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Shoe)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Shoe.ShoeDescription)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.WhislistId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Frameworks_ThatSneakerShop/Views/Whislists/Edit.cshtml
@model Frameworks_ThatSneakerShop.Models.Whislist

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Whislist</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="WhislistId" />
            <div class="form-group">
                <label asp-for="ShoeId" class="control-label"></label>
                <select asp-for="ShoeId" class="form-control" asp-items="ViewBag.ShoeId"></select>
                <span asp-validation-for="ShoeId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Frameworks_ThatSneakerShop/Views/Whislists/Index.cshtml
@model IEnumerable<Frameworks_ThatSneakerShop.Models.Whislist>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>

<form method="get" asp-action="Index" asp-controller="Whislist">
    <p>
        <input type="text" name="search" value=@ViewData["searchField"] />
        <input type="submit" value = "Search" />
    </p>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Shoe)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
            <tr>
                @if (item.Hidden == false)
                {

                    <td>
                        @Html.DisplayFor(modelItem => item.Shoe.ShoeName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Shoe.ShoeDescription)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Shoe.ShoePrice)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.WhislistId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.WhislistId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.WhislistId">Delete</a>
            </td>

            }
        </tr>
}

        @using (Html.BeginForm("UpdateData", "Whislists", FormMethod.Post))
        {
                <button type="submit">Show All Data</button>
        }
    </tbody>
</table>