Frameworks_ThatSneakerShop/Models/Payment.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Frameworks_ThatSneakerShop.Models {
    public class Payment {
        [Key]
        public int PaymentId { get; set; }


        [Required]
        [DataType(DataType.Currency)]
        [Display(Name = "Amount")]
        public float TotalOrder { get; set; }

        [Required]
        [DataType(DataType.DateTime)]
        [Display(Name = "Time of payment")]
        public DateTime TimeOfPayment { get; set; }

        [DefaultValue(false)]
        [Display(Name = "Available")]
        public bool Hidden { get; set; }
    }
}

Frameworks_ThatSneakerShop/Controllers/PaymentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Frameworks_ThatSneakerShop.Data;
using Frameworks_ThatSneakerShop.Models;

namespace Frameworks_ThatSneakerShop.Controllers
{
    public class PaymentsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PaymentsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Payments
        public async Task<IActionResult> Index()
        {
              return View(await _context.Payment.ToListAsync());
        }

        // GET: Payments/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Payment == null)
            {
                return NotFound();
            }

            var payment = await _context.Payment
                .FirstOrDefaultAsync(m => m.PaymentId == id);
            if (payment == null)
            {
                return NotFound();
            }

            return View(payment);
        }

        // GET: Payments/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Payments/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PaymentId")] Payment payment)
        {
            if (ModelState.IsValid)
            {
                _context.Add(payment);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(payment);
        }

        // GET: Payments/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Payment == null)
            {
                return NotFound();
            }

            var payment = await _context.Payment.FindAsync(id);
            if (payment == null)
            {
                return NotFound();
            }
            return View(payment);
        }

        // POST: Payments/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PaymentId")] Payment payment)
        {
            if (id != payment.PaymentId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(payment);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PaymentExists(payment.PaymentId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(payment);
        }

        // GET: Payments/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            //if (id == null || _context.Payment == null)
            //{
            //    return NotFound();
            //}

            //var payment = await _context.Payment
            //    .FirstOrDefaultAsync(m => m.PaymentId == id);
            //if (payment == null)
            //{
            //    return NotFound();
            //}

            //return View(payment);


            var payment = _context.Payment.Find(id);
            if (payment == null)
            {
                // Category not found
                return NotFound();
            }

            // Ik gebruik gewoon mijn property bool Hidden om deze te verstoppen 
            // In de cshtml doe ik een if else structuur om deze te verstoppen of te tonen 
            payment.Hidden = true;
            _context.SaveChanges();

            // Redirect the user back to the view
            return RedirectToAction(nameof(Index));
        }

        [HttpPost, ActionName("UpdateData")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateData(bool hidden) {
            var payments = _context.Payment.Where(p => p.Hidden == true);

            foreach (var payment in payments) {
                payment.Hidden = false;
            }
            _context.SaveChanges();

            // Redirect the user back to the view 
            return RedirectToAction(nameof(Index));
        }


        // POST: Payments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Payment == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Payment'  is null.");
            }
            var payment = await _context.Payment.FindAsync(id);
            if (payment != null)
            {
                _context.Payment.Remove(payment);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PaymentExists(int id)
        {
          return _context.Payment.Any(e => e.PaymentId == id);
        }
    }
}

Frameworks_ThatSneakerShop/Views/Payments/Create.cshtml
@model Frameworks_ThatSneakerShop.Models.Payment

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Payment</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Frameworks_ThatSneakerShop/Views/Payments/Delete.cshtml
@model Frameworks_ThatSneakerShop.Models.Payment

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Payment</h4>
    <hr />
    <dl class="row">
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="PaymentId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Frameworks_ThatSneakerShop/Views/Payments/Details.cshtml
@model Frameworks_ThatSneakerShop.Models.Payment

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Payment</h4>
    <hr />
    <dl class="row">
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.PaymentId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Frameworks_ThatSneakerShop/Views/Payments/Edit.cshtml
@model Frameworks_ThatSneakerShop.Models.Payment

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Payment</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="PaymentId" />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Frameworks_ThatSneakerShop/Views/Payments/Index.cshtml
@model IEnumerable<Frameworks_ThatSneakerShop.Models.Payment>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
                @if (item.Hidden == false) {
                }
            <td>
                <a asp-action="Edit" asp-route-id="@item.PaymentId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.PaymentId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.PaymentId">Delete</a>
            </td>
        </tr>
}

        @using (Html.BeginForm("UpdateData", "Payments", FormMethod.Post))
        {
            <button type="submit">Show All Data</button>
        }
    </tbody>
</table>